### ISSUE TITLE
Popup if a session of Catalyst is already open

### ISSUE THREAD

**Issue by jdev082** [CatalystDevOrg/Catalyst#103]
To prevent users from reporting a bug where, config will only apply to one window of Catalyst have a message popup if the user already has a window of Catalyst open. Preventing them from launching 2 sessions. Like Firefox or chr00m3

**Comment by webdev03** [comment]
Firefox doesn't warn you as far as I know. And also, I think config does apply to both sessions.

**Comment by JaydenDev** [comment]
When I open 2 Windows of Catalyst (Windows, not tabs, not the OS either). I can have dark mode enabled on the first one, but not the second. No settings changed in either.

**Comment by webdev03** [comment]
> not the OS either

🤣 
Ok, let me try to see what happens

**Comment by JaydenDev** [comment]
@webdev03 YOU have bene given write access DONT MAKE ME REGRET IT

**Comment by webdev03** [comment]
OK! I'll just work on my fork and make PRs I guess. Don't want to make any changes without your permission.

**Comment by webdev03** [comment]
Could I start working on the website in another repo?

**Comment by JaydenDev** [comment]
> OK! I'll just work on my fork and make PRs I guess, only write if I need something done emergency. Don't want to make any changes without your permission.

If I approve of the feature its fine.

**Comment by webdev03** [comment]
Config doesn't auto update when localStorage is changed, but it does when you open preferences. I don't think this is a real issue, but one thing that is a major issue is that when you open a new window it won't open the tab.

**Comment by webdev03** [comment]
Wait, how did you open two windows of Catalyst at once?

**Comment by JaydenDev** [comment]
> Wait, how did you open two windows of Catalyst at once? I tried to use `window.open`

I pressed WIN + B which is my keybind to run "catalyst"

**Comment by webdev03** [comment]
Wow cool!

**Comment by webdev03** [comment]
Can you send screenshot?

**Comment by JaydenDev** [comment]
Can't, I can't use copy paste image in Catalyst

**Comment by JaydenDev** [comment]
It's the same thing as clicking Catalyst in the task bar

**Comment by webdev03** [comment]
I can't open two Catalyst windows at once though.

**Comment by JaydenDev** [comment]
@webdev03 you can, just run the binary in terminal.

**Comment by webdev03** [comment]
https://github.com/JaydenDev/Catalyst/issues/103#issuecomment-1001740456

**Comment by JaydenDev** [comment]
not needed, closing.

**Comment by jdev082** [comment]
We should add this!
