### ISSUE TITLE
Package for Flatpak

### ISSUE THREAD

**Issue by VelocityDesign** [CatalystDevOrg/Catalyst#194]
### Is your feature request related to a problem? Please describe.

Some systems don't have support for the packages here. Additionally, flatpaks are sandboxed and more secure by design.

### Describe the solution you would like!

Building this as a Flatpak would allow more systems to have access to the browser. It should be easy to build a flatpak from the Debian package.

### Describe alternatives you have considered.

Snaps are an alternative to flatpaks, but they are often frowned upon by the Open community.

**Comment by JaydenDev** [comment]
I do in fact have a system running Fedora, I do not have the required knowlege or resources to distribute a flatpak package. Also, these packages would have to be made manually so they would become outdated anyway. If you wish to provide these pages, or make an automatic way to do so, that would be much appreciated.

**Comment by webdev03** [comment]
I don't know about flatpak, but would https://www.electronforge.io/config/makers/flatpak work?

**Comment by JaydenDev** [comment]
> I don't know about flatpak, but would https://www.electronforge.io/config/makers/flatpak work?

or even more difficult, making it work with GitHub actions, and uploading it to flathub (manually D:)

**Comment by JaydenDev** [comment]
Is flatpak really neccesary? Just run binaries, or use the RPM package. If you are intentionally using a distribution that requires flatpaks thats on you.

**Comment by JaydenDev** [comment]
@webdev03 I got the config in package.json working, you just need to add it to the gh actions. I've been at it for 30 minutes now haven't found out what I'm doing.

**Comment by webdev03** [comment]
I need to? Why do I have to?

**Comment by JaydenDev** [comment]
> I need to? Why do I have to?

Your the only one that knows how, lmao. You made the action.

**Comment by VelocityDesign** [comment]
> Is flatpak really neccesary? Just run binaries, or use the RPM package. If you are intentionally using a distribution that requires flatpaks thats on you.

I'm not using silverblue anymore, just fedora. However, flatpaks can be very helpful.

**Comment by JaydenDev** [comment]
> > Is flatpak really neccesary? Just run binaries, or use the RPM package. If you are intentionally using a distribution that requires flatpaks thats on you.
> 
> I'm not using silverblue anymore, just fedora. However, flatpaks can be very helpful.

in what way? lmao

**Comment by webdev03** [comment]
> > I need to? Why do I have to?
> 
> Your the only one that knows how, lmao. You made the action.

You know I'm not a linux person.... how would I know?

**Comment by JaydenDev** [comment]
> > > I need to? Why do I have to?
> > 
> > 
> > Your the only one that knows how, lmao. You made the action.
> 
> You know I'm not a linux person.... how would I know?

Wouldn't it be the same as when you added M1 builds? 'npm run make' ran on fedora would already produce a flatpak.

**Comment by webdev03** [comment]
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners doesn't have fedora?

**Comment by JaydenDev** [comment]
> Contributor
I'm sure you can do the flatpak with Ubuntu though.

**Comment by JaydenDev** [comment]
> https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners doesn't have fedora?

I'm sure you can do the flatpak with Ubuntu though.

**Comment by webdev03** [comment]
OK, so, just add the flatpak builder.

**Comment by JaydenDev** [comment]
> OK, so, just add the flatpak builder.

yes i think anyway

**Comment by jdev082** [comment]
Coming back to this!

**Comment by imdevarsh** [comment]
Maybe try https://docs.flatpak.org/en/latest/electron.html ?

**Comment by jdev082** [comment]
I have added flatpak build support in commit [ef747ea](https://github.com/CatalystDevOrg/Catalyst/commit/ef747eae281a9984b5a9347293787acda514da21)!

**Comment by jdev082** [comment]
1. The flatpak doesnt install
2. Gh action

**Comment by jdev082** [comment]
@mdwalters has volunteered

**Comment by jdev082** [comment]
Flatpak packaging has been implemented in [3b7f078](https://github.com/CatalystDevOrg/Catalyst/commit/3b7f078e79397ef99c9787deb42ee991cba048a6)!

**Comment by jdev082** [comment]
The implementation broke the build system and was reverted.

**Comment by faveoled** [comment]
@jdev082 
See my Flathub manifest submission: https://github.com/flathub/flathub/pull/4821

**Comment by icarusinthewings** [comment]
I was surprised to see my icon design on the flathub page! Keep up the excellent work, everyone!

**Comment by jdev082** [comment]
Pleased to say this feature is now officially implemented!
